public class ctaRecordTypeId 
{
    Public Static String Sampling = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Sampling').getRecordTypeId();
    Public Static String Contact = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Contact Us').getRecordTypeId();
    Public Static String demo = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Get A Demo').getRecordTypeId();
    Public Static String gmdesign = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('GM Design Guide').getRecordTypeId();
    Public Static String MailEnq = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Mail enquiry').getRecordTypeId();
    Public Static String Webinar = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Masterclass').getRecordTypeId();
    Public Static String callback = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Request Callback').getRecordTypeId();
    Public Static String customPrice = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Customized Price').getRecordTypeId();
    Public Static String ecom = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('eCommerce').getRecordTypeId();
    Public Static String quatation = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Quotation').getRecordTypeId();
    Public Static String indiaMart = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Indiamart').getRecordTypeId(); 
    Public Static String tradeIndia = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('TradeIndia').getRecordTypeId();
    Public Static String abandonedCart = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Abandoned Cart').getRecordTypeId();
    Public Static String WebEnq = schema.SObjectType.CTA__c.getRecordTypeInfosByName().get('Web Enquiry').getRecordTypeId();
}